[package]
org = "ballerina"
name = "websocket"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "../websocket-native/build/libs/websocket-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "websocket"
version = "@project.version@"

[[platform.java11.dependency]]
path = "./lib/http-native-@stdlib.httpnative.version@.jar"
groupId = "ballerina"
artifactId = "http"
version = "@stdlib.httpnative.version@"

[[platform.java11.dependency]]
path = "./lib/mime-native-@stdlib.mimenative.version@.jar"
groupId = "ballerina"
artifactId = "mime-native"
version = "@stdlib.mimenative.version@"

[[platform.java11.dependency]]
path = "./lib/netty-common-@netty.version@.jar"
groupId = "io.netty"
artifactId = "netty-common"
version = "@netty.version@"

[[platform.java11.dependency]]
path = "./lib/netty-buffer-@netty.version@.jar"
groupId = "io.netty"
artifactId = "netty-buffer"
version = "@netty.version@"

[[platform.java11.dependency]]
path = "./lib/netty-transport-@netty.version@.jar"
groupId = "io.netty"
artifactId = "netty-transport"
version = "@netty.version@"

[[platform.java11.dependency]]
path = "./lib/netty-resolver-@netty.version@.jar"
groupId = "io.netty"
artifactId = "netty-resolver"
version = "@netty.version@"

[[platform.java11.dependency]]
path = "./lib/netty-handler-@netty.version@.jar"
groupId = "io.netty"
artifactId = "netty-handler"
version = "@netty.version@"

[[platform.java11.dependency]]
path = "./lib/netty-codec-http-@netty.version@.jar"
groupId = "io.netty"
artifactId = "netty-codec-http"
version = "@netty.version@"

[[platform.java11.dependency]]
path = "./lib/netty-codec-@netty.version@.jar"
groupId = "io.netty"
artifactId = "netty-codec"
version = "@netty.version@"

[[platform.java11.dependency]]
path = "./lib/netty-handler-proxy-@netty.version@.jar"
groupId = "io.netty"
artifactId = "netty-handler-proxy"
version = "@netty.version@"

[[platform.java11.dependency]]
path = "./lib/netty-codec-http2-@netty.version@.jar"
groupId = "io.netty"
artifactId = "netty-codec-http2"
version = "@netty.version@"

[[platform.java11.dependency]]
path = "./lib/commons-pool-@commmon.pool.version@.jar"
groupId = "commons-pool.wso2"
artifactId = "commons-pool"
version = "@commmon.pool.version@"

[[platform.java11.dependency]]
path = "./lib/snakeyaml-@snakeyaml.version@.jar"
groupId = "org.wso2.orbit.org.yaml"
artifactId = "snakeyaml"
version = "@snakeyaml.version@"

[[platform.java11.dependency]]
path = "./lib/bcprov-jdk15on-@bouncycastle.version@.jar"
groupId = "org.bouncycastle"
artifactId = "bcprov-jdk15on"
version = "@bouncycastle.version@"

[[platform.java11.dependency]]
path = "./lib/bcpkix-jdk15on-@bouncycastle.version@.jar"
groupId = "org.bouncycastle"
artifactId = "bcpkix-jdk15on"
version = "@bouncycastle.version@"

[[platform.java11.dependency]]
path = "./lib/netty-tcnative-boringssl-static-@tcnative.version@.jar"
groupId = "io.netty"
artifactId = "netty-tcnative-boringssl-static"
version = "@tcnative.version@"

[[platform.java11.dependency]]
path = "./lib/mimepull-@mimepull.version@.jar"
groupId = "org.jvnet.mimepull"
artifactId = "mimepull"
version = "@mimepull.version@"
